spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eventify_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: emadeyad063@gmail.com
    password: opsdfbxsacgmhqij
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        transport:
          protocol: smtp
  jackson:
    serialization:
      fail-on-empty-beans: false

  application:
    name: 'Eventify'

server :
  port: 8091

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.mail: DEBUG
    org.springframework.web: DEBUG
