spring:
  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8091}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html

logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.springframework.mail: DEBUG
    org.springframework.web: DEBUG

app:
  base-url: https://eventify-uq0f.onrender.com
